### ISSUE TITLE
Compiling on MacOS: `error: no member named 'aligned_alloc' in namespace 'std'`

### ISSUE THREAD

**Issue by dschiller** [free-audio/clap-plugins#1]
When compiling on MacOS Catalina 10.15.7 (19H524) with `cmake --build --preset ninja-system` or with `scripts/build.sh` it fails with:

```
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/../audio-buffer.hh:21:35: error: no member named 'aligned_alloc' in namespace 'std'; did you mean simply 'aligned_alloc'?
           _data(static_cast<T *>(std::aligned_alloc(32, channelCount * frameCount * sizeof(T)))) {
                                  ^~~~~~~~~~~~~~~~~~
                                  aligned_alloc
```

**Comment by abique** [comment]
Is it fixed now?

**Comment by dschiller** [comment]
Hi Alexandre, in case you asked me, no it is not fixed - or at least the error shifted to another one.

```
dirk.schiller@C02DT9UMML7H clap-plugins % cmake --build --preset ninja-system
[1/8] Building CXX object plugins/CMakeFiles/clap-plugins.dir/Debug/modules/svf-module.cc.o
FAILED: plugins/CMakeFiles/clap-plugins.dir/Debug/modules/svf-module.cc.o 
/Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCLAP_REMOTE_GUI -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -Dclap_plugins_EXPORTS -DCMAKE_INTDIR=\"Debug\" -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/builds/ninja-system/plugins/clap-plugins_autogen/include_Debug -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/yas/include -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/clap/include -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/io/. -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/clap-helpers/include -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Werror=return-type -Werror=unused-result -Wno-unused-parameter -Wuninitialized -Wvla -Wmultichar -Werror=non-virtual-dtor -Woverloaded-virtual -Wmost -Wsuper-class-method-mismatch -std=gnu++2a -MD -MT plugins/CMakeFiles/clap-plugins.dir/Debug/modules/svf-module.cc.o -MF plugins/CMakeFiles/clap-plugins.dir/Debug/modules/svf-module.cc.o.d -o plugins/CMakeFiles/clap-plugins.dir/Debug/modules/svf-module.cc.o -c /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/svf-module.cc
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/svf-module.cc:4:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/../value-types/enumerated-value-type.hh:5:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/../value-types/value-type.hh:6:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/../value-types/../audio-buffer.hh:22:24: warning: unknown attribute 'unlikely' ignored [-Wunknown-attributes]
         if (!_data) [[unlikely]]
                       ^
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/svf-module.cc:4:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/../value-types/enumerated-value-type.hh:27:38: error: implicit instantiation of undefined template 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >'
      const std::vector<std::string> _entries;
                                     ^
/Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/svf-module.cc:6:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/svf-module.hh:3:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/../domain-converter.hh:17:27: warning: unknown attribute 'likely' ignored [-Wunknown-attributes]
         if (in == _in) [[likely]]
                          ^
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/svf-module.cc:6:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/svf-module.hh:4:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/module.hh:11:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/../parameter.hh:15:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/../value-types/../smoothed-value.hh:35:28: warning: unknown attribute 'likely' ignored [-Wunknown-attributes]
         if (_steps > 0) [[likely]] {
                           ^
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/../value-types/../smoothed-value.hh:45:28: warning: unknown attribute 'likely' ignored [-Wunknown-attributes]
         if (_steps > 0) [[likely]] {
                           ^
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/svf-module.cc:27:10: error: no viable conversion from 'unique_ptr<clap::EnumeratedValueType>' to 'unique_ptr<clap::ValueType>'
         std::make_unique<EnumeratedValueType>(std::vector<std::string>{"LP", "BP", "HP"}, 0));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2426:28: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'typename __unique_if<EnumeratedValueType>::__unique_single' (aka 'unique_ptr<clap::EnumeratedValueType>') to 'const std::__1::unique_ptr<clap::ValueType, std::__1::default_delete<clap::ValueType> > &' for 1st argument
class _LIBCPP_TEMPLATE_VIS unique_ptr {
                           ^
/Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2490:21: note: candidate constructor template not viable: no known conversion from 'typename __unique_if<EnumeratedValueType>::__unique_single' (aka 'unique_ptr<clap::EnumeratedValueType>') to 'std::nullptr_t' (aka 'nullptr_t') for 1st argument
  _LIBCPP_CONSTEXPR unique_ptr(nullptr_t) _NOEXCEPT : __ptr_(pointer(), __default_init_tag()) {}
                    ^
/Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2518:3: note: candidate constructor not viable: no known conversion from 'typename __unique_if<EnumeratedValueType>::__unique_single' (aka 'unique_ptr<clap::EnumeratedValueType>') to 'std::__1::unique_ptr<clap::ValueType, std::__1::default_delete<clap::ValueType> > &&' for 1st argument
  unique_ptr(unique_ptr&& __u) _NOEXCEPT
  ^
/Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2527:3: note: candidate template ignored: requirement 'is_convertible<clap::EnumeratedValueType *, clap::ValueType *>::value' was not satisfied [with _Up = clap::EnumeratedValueType, _Ep = std::__1::default_delete<clap::EnumeratedValueType>]
  unique_ptr(unique_ptr<_Up, _Ep>&& __u) _NOEXCEPT
  ^
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/modules/module.hh:61:58: note: passing argument to parameter 'valueType' here
                              std::unique_ptr<ValueType> valueType);
                                                         ^
4 warnings and 2 errors generated.
[2/8] Building CXX object plugins/CMakeFiles/clap-plugins.dir/Debug/value-types/value-type.cc.o
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/value-type.cc:1:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/value-type.hh:6:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/../audio-buffer.hh:22:24: warning: unknown attribute 'unlikely' ignored [-Wunknown-attributes]
         if (!_data) [[unlikely]]
                       ^
1 warning generated.
[3/8] Building CXX object plugins/CMakeFiles/clap-plugins.dir/Debug/value-types/enumerated-value-type.cc.o
FAILED: plugins/CMakeFiles/clap-plugins.dir/Debug/value-types/enumerated-value-type.cc.o 
/Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCLAP_REMOTE_GUI -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -Dclap_plugins_EXPORTS -DCMAKE_INTDIR=\"Debug\" -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/builds/ninja-system/plugins/clap-plugins_autogen/include_Debug -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/yas/include -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/clap/include -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/io/. -I/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/clap-helpers/include -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Werror=return-type -Werror=unused-result -Wno-unused-parameter -Wuninitialized -Wvla -Wmultichar -Werror=non-virtual-dtor -Woverloaded-virtual -Wmost -Wsuper-class-method-mismatch -std=gnu++2a -MD -MT plugins/CMakeFiles/clap-plugins.dir/Debug/value-types/enumerated-value-type.cc.o -MF plugins/CMakeFiles/clap-plugins.dir/Debug/value-types/enumerated-value-type.cc.o.d -o plugins/CMakeFiles/clap-plugins.dir/Debug/value-types/enumerated-value-type.cc.o -c /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/enumerated-value-type.cc
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/enumerated-value-type.cc:6:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/enumerated-value-type.hh:5:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/value-type.hh:6:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/../audio-buffer.hh:22:24: warning: unknown attribute 'unlikely' ignored [-Wunknown-attributes]
         if (!_data) [[unlikely]]
                       ^
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/enumerated-value-type.cc:6:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/enumerated-value-type.hh:27:38: error: implicit instantiation of undefined template 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >'
      const std::vector<std::string> _entries;
                                     ^
/Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/enumerated-value-type.cc:10:70: error: implicit instantiation of undefined template 'std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >'
   EnumeratedValueType::EnumeratedValueType(std::vector<std::string> entries, uint32_t defaultIndex)
                                                                     ^
/Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
1 warning and 2 errors generated.
[4/8] Building CXX object plugins/CMakeFiles/clap-plugins.dir/Debug/value-types/simple-value-type.cc.o
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/simple-value-type.cc:4:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/simple-value-type.hh:5:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/value-type.hh:6:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/../audio-buffer.hh:22:24: warning: unknown attribute 'unlikely' ignored [-Wunknown-attributes]
         if (!_data) [[unlikely]]
                       ^
1 warning generated.
[5/8] Building CXX object plugins/CMakeFiles/clap-plugins.dir/Debug/value-types/decibel-value-type.cc.o
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/decibel-value-type.cc:4:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/decibel-value-type.hh:5:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/value-type.hh:6:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/../audio-buffer.hh:22:24: warning: unknown attribute 'unlikely' ignored [-Wunknown-attributes]
         if (!_data) [[unlikely]]
                       ^
1 warning generated.
[6/8] Building CXX object plugins/CMakeFiles/clap-plugins.dir/Debug/value-types/frequency-value-type.cc.o
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/frequency-value-type.cc:4:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/frequency-value-type.hh:5:
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/value-type.hh:6:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/../audio-buffer.hh:22:24: warning: unknown attribute 'unlikely' ignored [-Wunknown-attributes]
         if (!_data) [[unlikely]]
                       ^
In file included from /Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/frequency-value-type.cc:4:
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/frequency-value-type.hh:24:20: warning: private field '_minValue' is not used [-Wunused-private-field]
      const double _minValue;
                   ^
/Volumes/K2TB/Work/Coding/CLAP/clap-plugins/plugins/value-types/frequency-value-type.hh:25:20: warning: private field '_maxValue' is not used [-Wunused-private-field]
      const double _maxValue;
                   ^
3 warnings generated.
ninja: build stopped: subcommand failed.
```

**Comment by abique** [comment]
Which compiler are you using?
The code seems valid to me and it compiles in the github actions as well.

**Comment by dschiller** [comment]
How can I find out ?

I believe it is `gcc`.

**Comment by abique** [comment]
`c++ --version`

**Comment by dschiller** [comment]
```
dirk.schiller@C02DT9UMML7H ~ % c++ --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Volumes/K2TB/Intel/Catalina/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
